### ISSUE TITLE
Bug: the avatar link is said to be optional but it is required in db schema

### ISSUE THREAD

**Issue by cawel** [FelixPriori/side-quests#4]
## Bug Description

When registering, the avatar link is said to be optional in the UI but it is actually required in db schema. Indeed, there is a "not null" constraint in the db schema for the `avatar` column.

Screenshot:

![register](https://user-images.githubusercontent.com/15407/80512943-4c5e7500-894c-11ea-8fe6-aa7a93b71109.png)

## Suggested Fix

* Either the "not null" db constraint is removed or that profile field becomes mandatory in the UI. I have a strong preference for the latter.

**Comment by FelixPriori** [comment]
Hi cawel,

There is a check being made in the file `back-end/routes/register.js` at line 27-29 that will insert a default avatar if one is not inserted by the user. 

Thanks for your report!

**Comment by cawel** [comment]
@FelixPriori Indeed, oversight on my part!
